// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v6.30.0
// source: vm.proto

package proto_vm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateVMReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVMReq) Reset() {
	*x = CreateVMReq{}
	mi := &file_vm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVMReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVMReq) ProtoMessage() {}

func (x *CreateVMReq) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVMReq.ProtoReflect.Descriptor instead.
func (*CreateVMReq) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{0}
}

type CreateVMResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVMResp) Reset() {
	*x = CreateVMResp{}
	mi := &file_vm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVMResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVMResp) ProtoMessage() {}

func (x *CreateVMResp) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVMResp.ProtoReflect.Descriptor instead.
func (*CreateVMResp) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{1}
}

func (x *CreateVMResp) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type DestroyVMReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyVMReq) Reset() {
	*x = DestroyVMReq{}
	mi := &file_vm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyVMReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyVMReq) ProtoMessage() {}

func (x *DestroyVMReq) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyVMReq.ProtoReflect.Descriptor instead.
func (*DestroyVMReq) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{2}
}

type DestroyVMResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyVMResp) Reset() {
	*x = DestroyVMResp{}
	mi := &file_vm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyVMResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyVMResp) ProtoMessage() {}

func (x *DestroyVMResp) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyVMResp.ProtoReflect.Descriptor instead.
func (*DestroyVMResp) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{3}
}

func (x *DestroyVMResp) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type StartVMReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVMReq) Reset() {
	*x = StartVMReq{}
	mi := &file_vm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVMReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVMReq) ProtoMessage() {}

func (x *StartVMReq) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVMReq.ProtoReflect.Descriptor instead.
func (*StartVMReq) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{4}
}

type StartVMResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVMResp) Reset() {
	*x = StartVMResp{}
	mi := &file_vm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVMResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVMResp) ProtoMessage() {}

func (x *StartVMResp) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVMResp.ProtoReflect.Descriptor instead.
func (*StartVMResp) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{5}
}

func (x *StartVMResp) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type StopVMReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopVMReq) Reset() {
	*x = StopVMReq{}
	mi := &file_vm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopVMReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopVMReq) ProtoMessage() {}

func (x *StopVMReq) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopVMReq.ProtoReflect.Descriptor instead.
func (*StopVMReq) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{6}
}

type StopVMResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopVMResp) Reset() {
	*x = StopVMResp{}
	mi := &file_vm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopVMResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopVMResp) ProtoMessage() {}

func (x *StopVMResp) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopVMResp.ProtoReflect.Descriptor instead.
func (*StopVMResp) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{7}
}

func (x *StopVMResp) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type RenewVMReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Day           int32                  `protobuf:"varint,1,opt,name=day,proto3" json:"day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewVMReq) Reset() {
	*x = RenewVMReq{}
	mi := &file_vm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewVMReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewVMReq) ProtoMessage() {}

func (x *RenewVMReq) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewVMReq.ProtoReflect.Descriptor instead.
func (*RenewVMReq) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{8}
}

func (x *RenewVMReq) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

type RenewVMResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewVMResp) Reset() {
	*x = RenewVMResp{}
	mi := &file_vm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewVMResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewVMResp) ProtoMessage() {}

func (x *RenewVMResp) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewVMResp.ProtoReflect.Descriptor instead.
func (*RenewVMResp) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{9}
}

func (x *RenewVMResp) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type GetVMInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVMInfoReq) Reset() {
	*x = GetVMInfoReq{}
	mi := &file_vm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVMInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVMInfoReq) ProtoMessage() {}

func (x *GetVMInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVMInfoReq.ProtoReflect.Descriptor instead.
func (*GetVMInfoReq) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{10}
}

type GetVMInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVMInfoResp) Reset() {
	*x = GetVMInfoResp{}
	mi := &file_vm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVMInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVMInfoResp) ProtoMessage() {}

func (x *GetVMInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVMInfoResp.ProtoReflect.Descriptor instead.
func (*GetVMInfoResp) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{11}
}

func (x *GetVMInfoResp) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

var File_vm_proto protoreflect.FileDescriptor

var file_vm_proto_rawDesc = string([]byte{
	0x0a, 0x08, 0x76, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x5f, 0x76, 0x6d, 0x22, 0x0d, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x4d,
	0x52, 0x65, 0x71, 0x22, 0x26, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x4d, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x44,
	0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x56, 0x4d, 0x52, 0x65, 0x71, 0x22, 0x27, 0x0a, 0x0d, 0x44,
	0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x56, 0x4d, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0x0c, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x72, 0x74, 0x56, 0x4d, 0x52,
	0x65, 0x71, 0x22, 0x25, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x72, 0x74, 0x56, 0x4d, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x0b, 0x0a, 0x09, 0x53, 0x74, 0x6f,
	0x70, 0x56, 0x4d, 0x52, 0x65, 0x71, 0x22, 0x24, 0x0a, 0x0a, 0x53, 0x74, 0x6f, 0x70, 0x56, 0x4d,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x1e, 0x0a, 0x0a,
	0x52, 0x65, 0x6e, 0x65, 0x77, 0x56, 0x4d, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x61,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x64, 0x61, 0x79, 0x22, 0x25, 0x0a, 0x0b,
	0x52, 0x65, 0x6e, 0x65, 0x77, 0x56, 0x4d, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x56, 0x4d, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x22, 0x27, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x56, 0x4d, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0xf3, 0x02, 0x0a,
	0x09, 0x56, 0x4d, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x12, 0x3b, 0x0a, 0x08, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x56, 0x4d, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x76,
	0x6d, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x4d, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x76, 0x6d, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56,
	0x4d, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x09, 0x44, 0x65, 0x73, 0x74, 0x72,
	0x6f, 0x79, 0x56, 0x4d, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x76, 0x6d, 0x2e,
	0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x56, 0x4d, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x76, 0x6d, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x56,
	0x4d, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x07, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x56, 0x4d, 0x12, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x76, 0x6d, 0x2e, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x56, 0x4d, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x5f, 0x76, 0x6d, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x56, 0x4d, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x00, 0x12, 0x35, 0x0a, 0x06, 0x53, 0x74, 0x6f, 0x70, 0x56, 0x4d, 0x12, 0x13, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x5f, 0x76, 0x6d, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x56, 0x4d, 0x52, 0x65, 0x71,
	0x1a, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x76, 0x6d, 0x2e, 0x53, 0x74, 0x6f, 0x70,
	0x56, 0x4d, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x07, 0x52, 0x65, 0x6e, 0x65,
	0x77, 0x56, 0x4d, 0x12, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x76, 0x6d, 0x2e, 0x52,
	0x65, 0x6e, 0x65, 0x77, 0x56, 0x4d, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x5f, 0x76, 0x6d, 0x2e, 0x52, 0x65, 0x6e, 0x65, 0x77, 0x56, 0x4d, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x00, 0x12, 0x3e, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x56, 0x4d, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x76, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x4d,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f,
	0x76, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x4d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x76,
	0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_vm_proto_rawDescOnce sync.Once
	file_vm_proto_rawDescData []byte
)

func file_vm_proto_rawDescGZIP() []byte {
	file_vm_proto_rawDescOnce.Do(func() {
		file_vm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vm_proto_rawDesc), len(file_vm_proto_rawDesc)))
	})
	return file_vm_proto_rawDescData
}

var file_vm_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_vm_proto_goTypes = []any{
	(*CreateVMReq)(nil),   // 0: proto_vm.CreateVMReq
	(*CreateVMResp)(nil),  // 1: proto_vm.CreateVMResp
	(*DestroyVMReq)(nil),  // 2: proto_vm.DestroyVMReq
	(*DestroyVMResp)(nil), // 3: proto_vm.DestroyVMResp
	(*StartVMReq)(nil),    // 4: proto_vm.StartVMReq
	(*StartVMResp)(nil),   // 5: proto_vm.StartVMResp
	(*StopVMReq)(nil),     // 6: proto_vm.StopVMReq
	(*StopVMResp)(nil),    // 7: proto_vm.StopVMResp
	(*RenewVMReq)(nil),    // 8: proto_vm.RenewVMReq
	(*RenewVMResp)(nil),   // 9: proto_vm.RenewVMResp
	(*GetVMInfoReq)(nil),  // 10: proto_vm.GetVMInfoReq
	(*GetVMInfoResp)(nil), // 11: proto_vm.GetVMInfoResp
}
var file_vm_proto_depIdxs = []int32{
	0,  // 0: proto_vm.VMManager.CreateVM:input_type -> proto_vm.CreateVMReq
	2,  // 1: proto_vm.VMManager.DestroyVM:input_type -> proto_vm.DestroyVMReq
	4,  // 2: proto_vm.VMManager.StartVM:input_type -> proto_vm.StartVMReq
	6,  // 3: proto_vm.VMManager.StopVM:input_type -> proto_vm.StopVMReq
	8,  // 4: proto_vm.VMManager.RenewVM:input_type -> proto_vm.RenewVMReq
	10, // 5: proto_vm.VMManager.GetVMInfo:input_type -> proto_vm.GetVMInfoReq
	1,  // 6: proto_vm.VMManager.CreateVM:output_type -> proto_vm.CreateVMResp
	3,  // 7: proto_vm.VMManager.DestroyVM:output_type -> proto_vm.DestroyVMResp
	5,  // 8: proto_vm.VMManager.StartVM:output_type -> proto_vm.StartVMResp
	7,  // 9: proto_vm.VMManager.StopVM:output_type -> proto_vm.StopVMResp
	9,  // 10: proto_vm.VMManager.RenewVM:output_type -> proto_vm.RenewVMResp
	11, // 11: proto_vm.VMManager.GetVMInfo:output_type -> proto_vm.GetVMInfoResp
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_vm_proto_init() }
func file_vm_proto_init() {
	if File_vm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vm_proto_rawDesc), len(file_vm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vm_proto_goTypes,
		DependencyIndexes: file_vm_proto_depIdxs,
		MessageInfos:      file_vm_proto_msgTypes,
	}.Build()
	File_vm_proto = out.File
	file_vm_proto_goTypes = nil
	file_vm_proto_depIdxs = nil
}
